export const ADD_SERVICE = 'ADD_SERVICE';
export const REMOVE_SERVICE = 'REMOVE_SERVICE';
export const EDIT_SERVICE = 'EDIT_SERVICE';
export const CANCEL_SERVICE = 'CANCEL_SERVICE';
export const CHANGE_SERVICE_FIELD = 'CHANGE_SERVICE_FIELD';