export const FETCH_SERVICES_REQUEST = 'FETCH_SERVICES_REQUEST';
export const FETCH_SERVICES_FAILURE = 'FETCH_SERVICES_FAILURE';
export const FETCH_SERVICES_SUCCESS = 'FETCH_SERVICES_SUCCESS';

export const FETCH_SERVICES_REMOVE_REQUEST = 'FETCH_SERVICES_REMOVE_REQUEST';
export const FETCH_SERVICES_REMOVE_FAILURE = 'FETCH_SERVICES_REMOVE_FAILURE';
export const FETCH_SERVICES_REMOVE_SUCCESS = 'FETCH_SERVICES_REMOVE_SUCCESS';

export const SERVICE_FORM_INPUT = 'SERVICE_FORM_INPUT';

export const FETCH_SERVICE_FORM_REQUEST = 'FETCH_SERVICE_FORM_REQUEST';
export const FETCH_SERVICE_FORM_FAILURE = 'FETCH_SERVICE_FORM_FAILURE';
export const FETCH_SERVICE_FORM_SUCCESS = 'FETCH_SERVICE_FORM_SUCCESS';

export const FETCH_SERVICE_FORM_SAVE_REQUEST = 'FETCH_SERVICE_FORM_SAVE_REQUEST';
export const FETCH_SERVICE_FORM_SAVE_FAILURE = 'FETCH_SERVICE_FORM_SAVE_FAILURE';
export const FETCH_SERVICE_FORM_SAVE_SUCCESS = 'FETCH_SERVICE_FORM_SAVE_SUCCESS';